vemey/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from main.views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^accounts/login/$', auth_views.login),
    url(r'^logout/$', logout_page),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home),

    url(r'^company/$', companies),
    url(r'^company/add/$', CompanyCreate.as_view(), name='company_create'),
    url(r'^company/(?P<company_id>\d+)/$', company_detail),
    url(r'^company/(?P<pk>\d+)/update/$', CompanyUpdate.as_view(), name='company_update'),

    url(r'^country/$', countries),
    url(r'^country/add/$', CountryCreate.as_view(), name='country_create'),
    url(r'^country/(?P<country_id>\d+)/$', country_detail),
    url(r'^country/(?P<pk>\d+)/update/$', CountryUpdate.as_view(), name='country_update'),
    url(r'^country/(?P<country_id>\d+)/city/add/$', CityCreate.as_view(), name='city_create'),

    url(r'^city/(?P<city_id>\d+)/$', city_detail),
    url(r'^city/(?P<pk>\d+)/update/$', CityUpdate.as_view(), name='city_update'),
    url(r'^city/$', cities),
    url(r'^city/(?P<city_id>\d+)/building/add/$', BuildingCreate.as_view(), name='building_create'),

    url(r'^building/(?P<building_id>\d+)/$', building_detail),
    url(r'^building/(?P<pk>\d+)/update/$', BuildingUpdate.as_view(), name='building_update'),
    url(r'^building/$', buildings),
    url(r'^building/(?P<building_id>\d+)/datacenterroom/add/$', DataCenterRoomCreate.as_view(),
        name='datacenterroom_create'),

    url(r'^datacenterroom/(?P<dc_id>\d+)/$', data_center_room),
    url(r'^datacenterroom/$', datacenterrooms),
    url(r'^datacenterroom/(?P<dc_id>\d+)/rack/add/$', RackCreate.as_view(), name='rack_create'),
    url(r'^datacenterroom/(?P<pk>\d+)/update/$', DataCenterRoomUpdate.as_view(), name='datacenterroom_update'),

    url(r'^rack/(?P<rack_id>\d+)/$', rack),
    url(r'^rack/$', racks),
    url(r'^rack/(?P<rack_id>\d+)/device/add/$', DeviceCreate.as_view(), name='device_create'),
    url(r'^rack/(?P<pk>\d+)/update/$', RackUpdate. as_view(), name='rack_update'),

    url(r'^device-type/$', device_types),
    url(r'^device-type/add/$', DeviceTypeCreate .as_view(), name='device_type_create'),
    url(r'^device-type/(?P<pk>\d+)/update/$', DeviceTypeUpdate.as_view(), name='device_type_update'),
    url(r'^device-type/(?P<device_type_id>\d+)/$', device_type),

    url(r'^device/(?P<device_id>\d+)/$', device),
    url(r'^device/$', devices),
    url(r'^device/(?P<device_id>\d+)/port/add/$', PortCreate.as_view(), name='port_create'),
    url(r'^device/(?P<pk>\d+)/update/$', DeviceUpdate.as_view(), name='device_update'),

    url(r'^port-type/$', port_types),
    url(r'^port-type/add/$', PortTypeCreate.as_view(), name='port_type_create'),
    url(r'^port-type/(?P<pk>\d+)/update/$', PortTypeUpdate.as_view(), name='port_type_update'),
    url(r'^port-type/(?P<port_type_id>\d+)/$', port_type),

    url(r'^port/(?P<port_id>\d+)/$', port),
    url(r'^port/$', ports),
    url(r'^port/(?P<pk>\d+ )/update/$', PortUpdate.as_view(), name='port_update'),
    url(r'^port/(?P<port_id>\d+)/connection/add/$', ConnectionCreate.as_view(), name='connection_create'),

    url(r'^connection/$', connections),
    url(r'^connection/(?P<connection_id>\d+)/$', connection),
]

main/models.py
# encoding: utf-8

from django.db import models
from django.db.models.signals import post_save
from django.dispatch.dispatcher import receiver
from django.db.models import Q
import datetime


# Create your models here.

class Company(models.Model):
    name = models.CharField(max_length=50)

    def get_absolute_url(self):
        return "/company/" + str(self.id) + "/"

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name_plural = u"Companies"


class Country(models.Model):
    name = models.CharField(max_length=50)
    iso_code = models.CharField(max_length=2)

    def get_absolute_url(self):
        return "/country/" + str(self.id) + "/"

    def __str__(self):
        return "%s" % self.iso_code

    class Meta:
        verbose_name_plural = u"Countries"


class City(models.Model):
    country = models.ForeignKey(Country)
    name = models.CharField(max_length=50)

    def get_absolute_url(self):
        return "/city/" + str(self.id) + "/"

    def __str__(self):
        return "%s - %s" % (self.country.iso_code, self.name)

    class Meta:
        verbose_name_plural = u"Cities"

    def location_string(self):
        return "%s" % self.country.name


class Building(models.Model):
    city = models.ForeignKey(City)
    name = models.CharField(max_length=50)

    def get_absolute_url(self):
        return "/building/" + str(self.id) + "/"

    def __str__(self):
        return "%s - %s" % (self.city, self.name)

    class Meta:
        verbose_name_plural = u"Buildings"

    def location_string(self):
        return "%s, %s" % (self.city.name, self.city.location_string())


class DataCenterRoom(models.Model):
    building = models.ForeignKey(Building)
    name = models.CharField(max_length=50)
    square_meter = models.SmallIntegerField()
    owner = models.ForeignKey(Company, related_name='dc_owner', null=True, blank=True)
    manager = models.ForeignKey(Company, related_name='dc_manager', null=True, blank=True)
    customer = models.ForeignKey(Company, related_name='dc_customer', null=True, blank=True)

    def get_absolute_url(self):
        return "/datacenterroom/" + str(self.id) + "/"

    def __str__(self):
        return "%s - %s" % (self.building.name, self.name)

    class Meta:
        verbose_name_plural = u"Data center rooms"

    def location_string(self):
        return "%s, %s" % (self.building.name, self.building.location_string())


class Rack(models.Model):
    datacenterroom = models.ForeignKey(DataCenterRoom)
    name = models.CharField(max_length=50)
    model = models.CharField(max_length=50, null=True, blank=True)
    owner = models.ForeignKey(Company, related_name='rack_owner', null=True, blank=True)
    manager = models.ForeignKey(Company, related_name='rack_manager', null=True, blank=True)
    customer = models.ForeignKey(Company, related_name='rack_customer', null=True, blank=True)
    height = models.SmallIntegerField(default=42)
    date_installed = models.DateField(default=datetime.date.today, null=True, blank=True)

    def get_absolute_url(self):
        return "/rack/" + str(self.id) + "/"

    def __str__(self):
        return "%s - %s" % (self.datacenterroom, self.name)

    class Meta:
        verbose_name_plural = u"Racks"

    def location_string(self):
        return "%s, %s" % (self.datacenterroom.name, self.datacenterroom.location_string())

    def number_of_empty_rack_units(self):
        empty_racks = 0
        for x in range(1, self.height+1):
            devices = None
            try:
                devices = Device.objects.filter(rack=self, rackunit__no=x)
            except:
                pass

            if not devices:
                empty_racks += 1

        return empty_racks

    def save(self):

        is_new_object = False

        old_height = None

        # nesne daha önce kayıtlı mıymış diye bakıyoruz.
        # böylelikle nesne ilk kez mi yaratılıyor, yoksa
        # update mi ediliyor anlıyoruz.
        try:
            old_obj = Rack.objects.get(pk=self.pk)
            old_height = old_obj.height
        except Rack.DoesNotExist: # yeni nesne
            is_new_object = True
        else:
            is_new_object = False

        # super metodunu burada çağırıyoruz çünkü önce rack'in save edilmesi
        # gerekiyor. rackunit'leri yaratırken bu rack'i kullanacağız.
        # update ediliyorsa sorun değil, update işleminden önceki "height"
        # değerini "old_height"a yazdık.
        super(Rack, self).save()

        # rack ilk kez yaratılıyor. "height" field'ında belirtilen kadar
        # rackunit yaratalım.
        if is_new_object:
            # 42u'luk bir rack ise for döngüsü range(1,43) için işliyor. yani min 1, max 42.
            for x in range(1, self.height+1):
                new_rack_unit = RackUnit(rack=self, no=x)
                new_rack_unit.save()

        # rack update ediliyor.
        else:
            if old_height:
                # eski rack'in rackunit sayısı update ile değiştirilmiş.
                # eksik veya fazla rackunitleri tespit edip düzeltme yapmak
                # lazım. şimdilik "pass" ile geçiştirilsin.
                if old_height != self.height:
                    # rackunit sayısı artırılmış.
                    if old_height < self.height:
                        pass
                    # rackunit sayısı azaltılmış.
                    else:
                        pass


class RackUnit(models.Model):
    rack = models.ForeignKey(Rack)
    no = models.SmallIntegerField(default=0)

    def __str__(self):
        return "%s-%dU" % (self.rack.name, self.no)

    def short_name(self):
        return "%dU" % self.no

    class Meta:
        verbose_name_plural = u"Rack Units"
        ordering = ('-no', )


class DeviceType(models.Model):
    name = models.CharField(max_length=50)
    has_paired_ports = models.BooleanField(default=False)

    def get_absolute_url(self):
        return "/device-type/" + str(self.id) + "/"

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name_plural = u"Device Types"
        ordering = ('name',)


class Device(models.Model):
    name = models.CharField(max_length=50)
    type = models.ForeignKey(DeviceType)
    manufacturer = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    serial = models.CharField(max_length=50)
    owner = models.ForeignKey(Company, related_name='device_owner')
    manager = models.ForeignKey(Company, related_name='device_manager')
    customer = models.ForeignKey(Company, related_name='device_customer', null=True, blank=True)
    rack = models.ForeignKey(Rack)
    rackunit = models.ManyToManyField(RackUnit)

    def get_absolute_url(self):
        return "/device/" + str(self.id) + "/"

    def __str__(self):
        return "%s (%s %s %s)" % (self.name, self.type, self.manufacturer, self.model)

    class Meta:
        verbose_name_plural = u"Devices"
        # ordering rack_first ve rack_last'a göre yapılıyordu.
        # yeni bir ordering belirlemek gerekiyor.
        ordering = ('rack', )

    def location_string(self):
        return "%s, %s" % (self.rack.name, self.rack.location_string())

    def rack_location(self):
        # {x}-{y}U representation of device's location in rack.
        # For a device located in 6,7,8,9 numbered rackunits return value is:
        #   6-9U
        rack_address_list = []
        for rackUnit in reversed(self.rackunit.all()):
            rack_address_list.append(str(rackUnit.no))

        if rack_address_list:
            # return "("+ ','.join(rack_address_list) + ")" + "U"
            return str(rack_address_list[0]) + "-" + str(rack_address_list[-1]) + "U"
        else:
            return ""

    def rack_size(self):
        # Number of rack units device allocates.
        return self.rackunit.all().count()

    def find_ports(self):
        device = self
        try:
            my_ports = list(Port.objects.filter(Q(device=device)))
        except:
            my_ports = []
        return my_ports

    def find_reserved_ports(self):
        pass

    def find_unreserved_ports(self):
        pass


class PortType(models.Model):
    name = models.CharField(max_length=50)

    def get_absolute_url(self):
        return "/port-type/" + str(self.id) + "/"

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name_plural = u"Port Types"


class Port(models.Model):
    type = models.ForeignKey(PortType)
    device = models.ForeignKey(Device)
    name = models.CharField(max_length=20)
    is_paired = models.BooleanField(default=False)
    pair_port = models.ForeignKey('self', null=True, blank=True, editable=False, on_delete=models.SET_NULL)

    def get_absolute_url(self):
        return "/port/" + str(self.id) + "/"

    def __str__(self):
        return "%s %s.Port (%s Type)" % (self.device, self.name, self.type)

    class Meta:
        verbose_name_plural = u"Ports"

    def find_connections(self):
        dedicated_cablings = []
        target_port = self
        cabling = self.get_single_cabling(target_port, dedicated_cablings)
        while cabling is not None:
            dedicated_cablings.append(cabling)
            if cabling.edge1 == target_port:
                target_port = cabling.edge2
            elif cabling.edge2 == target_port:
                target_port = cabling.edge1
            else:
                pass

            if target_port.is_paired:
                if target_port.pair_port is None:
                    target_port = target_port.pair_port

            cabling = self.get_single_cabling(target_port, dedicated_cablings)

        return dedicated_cablings

    def find_connection_edge(self):
        # start point is self
        target_port = self

        # loop over every cabling connected to each other.
        while True:
            # at every step, a new cabling is found, dedicated to target port.

templates/base.html
<!DOCTYPE html>
<html lang="tr">
<head>
<meta charset="utf-8">
<meta name="rating" content="General" >
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{% endblock %} | VeMEY</title>
{% block meta %}{% endblock %}
<link href="/static/img/favicon.ico" rel="icon" type="image/x-icon" />

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

{% block head %}{% endblock %}

<style>
	body { padding-top: 70px; }
</style>

</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">VeMEY</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="active"><a href="/">Home</a></li>
					<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Settings <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="/company/">Companies</a></li>
							<li><a href="/country/">Countries</a></li>
							<li><a href="/city/">Cities</a></li>
							<li><a href="/building/">Buildings</a></li>
							<li><a href="/device-type/">Device Types</a></li>
							<li><a href="/port-type/">Port Types</a></li>
						</ul>
					</li>
					<li><a href="/datacenterroom/">Data Center Rooms</a></li>
					<li><a href="/rack/">Racks</a></li>
					<li><a href="/device/">Devices</a></li>
					<li><a href="/port/">Ports</a></li>
					<li><a href="/connection/">Connections</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="/logout/">Sign out ({{user.username}})</a></li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				{% block content %}
				{% endblock %}
			</div>
		</div>
	</div>
</body>
</html>

templates/buildings.html
{% extends "base.html" %}
{% block title %}Buildings{% endblock %}
{% block meta %}
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="index,follow" />
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>Buildings</h1>
		</div>
		<ol class="breadcrumb">
			<li><a href="/">Home</a></li>
			<li class="active">Buildings</li>
		</ol>
	</div>
	<div class="col-md-12">
		<table class="table table-bordered table-striped">
			<tr>
				<th>Name</th>
				<th>City</th>
				<th>Country</th>
				<th>Country ISO-Code</th>
				<th>Update</th>
			</tr>
			{% for building in buildings %}
				<tr>
					<td><a href="{{building.get_absolute_url}}">{{building.name}}</a></td>
					<td><a href="{{building.city.get_absolute_url}}">{{building.city.name}}</a></td>
					<td><a href="{{building.city.country.get_absolute_url}}">{{building.city.country.name}}</a></td>
					<td>{{building.city.country.iso_code}}</td>
					<td><a class="btn btn-primary btn-sm" href="{{building.get_absolute_url}}update/" role="button">Update</a></td>
				</tr>
			{% endfor %}
		</table>
	</div>
</div>
{% endblock %}

templates/company_create.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block meta %}
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="index,follow" />
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<form action="." method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
				<div class="col-md-4">
					<div class="form-group">
						{{ field.errors }}
						{% if field.field.required %}
						{{ field.label_tag }} <span class="asterisk">*</span>
						{% else %}
						{{ field.label_tag }}
						{% endif %}
						{{ field }}
					</div>
				</div>
			{% endfor %}
			<div class="clearfix"></div>
			<div class="col-md-4">
			<button class="btn btn-lg btn-primary btn-block" type="submit">Save</button>
			</div>
			<div class="clearfix"></div>
		</form>
	</div>
</div>
{% endblock %}

templates/connections.html
{% extends "base.html" %}
{% block title %}Connections{% endblock %}
{% block meta %}
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="index,follow" />
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>Connections</h1>
		</div>
		<ol class="breadcrumb">
			<li><a href="/">Home</a></li>
			<li class="active">Connections</li>
		</ol>
	</div>
	<div class="col-md-12">
    {% if connections  %}
		<table class="table table-bordered table-striped">
			<tr>
				<th>Name</th>
				<th>Edge 1</th>
				<th>Edge 2</th>
			</tr>

			{% for connection in connections %}
				<tr>
					<td><a href="{{connection.get_absolute_url}}">{{connection.name}}</a></td>
					<td>{{connection.edge1}}</td>
					<td>{{connection.edge2}}</td>
				</tr>
			{% endfor %}
        </table>
    {% else %}
        <i> No records </i>
    {%  endif %}
    </div>
</div>
{% endblock %}

templates/countries.html
{% extends "base.html" %}
{% block title %}Countries{% endblock %}
{% block meta %}
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="index,follow" />
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>Countries</h1>
		</div>
		<ol class="breadcrumb">
			<li><a href="/">Home</a></li>
			<li class="active">Countries</li>
		</ol>
	</div>
	<div class="col-md-12" style="margin:10px;">
		<a class="btn btn-primary btn-sm" href="/country/add/" role="button">Add Country</a>
	</div>
	<div class="col-md-12">
		<table class="table table-bordered table-striped">
			<tr>
				<th>Name</th>
				<th>ISO-Code</th>
				<th>Update</th>
			</tr>
			{% for country in countries %}
				<tr>
					<td><a href="{{country.get_absolute_url}}">{{country.name}}</a></td>
					<td>{{country.iso_code}}</td>
					<td><a class="btn btn-primary btn-sm" href="{{country.get_absolute_url}}update/" role="button">Update</a></td>
				</tr>
			{% endfor %}
		</table>
	</div>
</div>
{% endblock %}

templates/country.html
{% extends "base.html" %}
{% block title %}{{country.iso_code}} {{country.name}}{% endblock %}
{% block meta %}
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="index,follow" />
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>{{country.iso_code}} <small>{{country.name}}</small></h1>
		</div>
		<ol class="breadcrumb">
			<li><a href="/">Home</a></li>
			<li><a href="/country/">Countries</a></li>
			<li class="active">{{country.name}}</li>
		</ol>
	</div>
	<div class="col-md-3">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Cities</h3>
			</div>
			<div class="panel-body">
				<p><a class="btn btn-primary btn-sm" href="{{country.get_absolute_url}}city/add/" role="button">Add City</a></p>
				{% if cities %}
					{% for city in cities %}
						<p><a href="{{city.get_absolute_url}}">{{city.name}}</a></p>
					{% endfor %}
				{% else %}
					<i>No records</i>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/datacenterroom_create.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block meta %}
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="index,follow" />
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<form action="." method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			{% for field in form %}
				<div class="col-md-4">
					<div class="form-group">
						{{ field.errors }}
						{% if field.field.required %}
						{{ field.label_tag }} <span class="asterisk">*</span>
						{% else %}
						{{ field.label_tag }}
						{% endif %}
						{{ field }}
					</div>
				</div>
			{% endfor %}
			<div class="clearfix"></div>
			<div class="col-md-4">
			<button class="btn btn-lg btn-primary btn-block" type="submit">Save</button>
			</div>
			<div class="clearfix"></div>
		</form>
	</div>
</div>
{% endblock %}

templates/device.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block meta %}
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="index,follow" />
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1><small>Device</small> {{device.brand}} {{device.model}} {{device.type}} <small>{{device.rack}}</small></h1>
		</div>
	</div>
	<div class="col-md-12">
		<p><a class="btn btn-primary btn-sm" href="{{device.get_absolute_url}}update/" role="button">Update</a></p>
		<table class="table table-bordered">
			<tr>
				<th>Name</th>
				<td>{{device.name}}</td>
			</tr>
            <tr>
				<th>Type</th>
				<td>{{device.type}}</td>
			</tr>
			<tr>
				<th>Manufacturer</th>
				<td>{{device.manufacturer}}</td>
			</tr>
			<tr>
				<th>Model</th>
				<td>{{device.model}}</td>
			</tr>
			<tr>
				<th>Serial</th>
				<td>{{device.serial}}</td>
			</tr>
			<tr>
				<th>Owner</th>
				<td>{{device.owner}}</td>
			</tr>
			<tr>
				<th>Manager</th>
				<td>{{device.manager}}</td>
			</tr>
			<tr>
				<th>Rack</th>
				<td>{{device.rack}}</td>
			</tr>
			<tr>
				<th>Rack Location</th>
				<td>{{device.rack_location}}</td>
			</tr>
		</table>
	</div>
	<div class="col-md-12" style="margin:10px;">
		<a class="btn btn-primary btn-sm" href="{{device.get_absolute_url}}port/add/" role="button">Add Port</a>
	</div>
	<div class="col-md-12">
		<h2>Reserved Ports</h2>
		<table class="table table-bordered table-striped">
			<tr>
				<th>Type</th>
				<th>Local Port</th>
				<th>Connected Port</th>
			</tr>
			{% for port in reserved_ports %}
				<tr>
					<td>{{port.type}}</td>
					<td><a href="{{port.get_absolute_url}}" title="{{port}}">{{port.name}}</a></td>
					<td><a href="{{port.find_connection_edge.get_absolute_url}}" title="{{port.find_connection_edge}}">{{port.find_connection_edge.name}}</a></td>
				</tr>
			{% endfor %}
		</table>
		<h2>Unreserved Ports</h2>
		<table class="table table-bordered table-striped">
			<tr>
				<th>Type</th>
				<th>Name</th>
			</tr>
			{% for port in unreserved_ports %}
				<tr>
					<td>{{port.type}}</td>
					<td><a href="{{port.get_absolute_url}}" title="{{port}}">{{port.name}}</a></td>
				</tr>
			{% endfor %}
		</table>
	</div>
</div>
{% endblock %}

templates/rack.html
{% extends "base.html" %}
{% block title %}Rack {{cabinet.name}}{% endblock %}
{% block meta %}
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="index,follow" />
{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1>Rack: {{rack.name}} <small>{{rack.row}}</small></h1>
		</div>
	</div>
	<div class="col-md-12" style="margin:10px;">
		<a class="btn btn-primary btn-sm" href="{{rack.get_absolute_url}}device/add/" role="button">Add Device</a>
	</div>
	<div class="col-md-12">
		<h2>Rack Units and Devices</h2>
		<table class="table table-bordered table-striped">
			<tr>
				<th>No</th>
				<th>Device</th>
			</tr>
			{% for rack_unit in rack_units %}
				<tr>
					<td>{{rack_unit.no}}</td>
					<td>
						{% for device in rack_unit.device_set.all %}
						<a href="{{device.get_absolute_url}}">{{device}}</a>
						{% if not forloop.last %}<br/> {% endif %}
						{% endfor %}
					</td>
				</tr>
			{% endfor %}
		</table>
	</div>
</div>
{% endblock %}